global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 2s

scrape_configs:
  - job_name: 'ml-api'
    scrape_interval: 2s
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']